### ISSUE TITLE
Missing option to request quote in some currency

### ISSUE THREAD

**Issue by grzegorzociepka** [alexeybusygin/ShippingRates#13]
Hey, there is an option in fedex api, to return the quote in currency that we want to have, also there is additional field which is saying which currency is it. Can you add this please? It would be very helpful. Or I can create PR, but please accept this :)

**Comment by alexeybusygin** [comment]
Hi! This work is already in progress and will be a part of a big DHL release. I expect to complete it by the end of this week.

**Comment by grzegorzociepka** [comment]
Great!
So there will be DHL option, and currency options for fedex?
Sorry for asking, just want to make sure.

**Comment by grzegorzociepka** [comment]
any updates?

**Comment by alexeybusygin** [comment]
Hi! The new release took a bit more time than expected. But now you can try the new package version 1.1.0. It has PreferredCurrencyCode in the ShipmentOptions for FedEx shipping.

**Comment by grzegorzociepka** [comment]
Thanks!
I'll let you know on monday if it's ok :)

**Comment by alexeybusygin** [comment]
Did you have a chance to check it?
