### ISSUE TITLE
FedEx provider exception on .NET Framework 4.8

### ISSUE THREAD

**Issue by martinrybak** [alexeybusygin/ShippingRates#14]
Thanks for maintaining this fork! I'm using version 1.1.0.96 on .NET Framework 4.8. UPS rates come back fine, but Fedex rates come back empty with the following InternalError:

```
FedEx provider exception: Error in line 1 position 169. Expecting element 'ExceptionDetail' from namespace
'http://schemas.datacontract.org/2004/07/System.ServiceModel'.. Encountered 'Element'  with name 'cause', namespace ''.
```

This issue does not occur on .NET Core.
It also does not occur with DotNetShipping on .NET Framework 4.8.

**Comment by alexeybusygin** [comment]
Hello Martin!

Could you please tell me the version of System.ServiceModel.Http package installed in your project?

**Comment by martinrybak** [comment]
I had `4.1.0` but upgraded to `4.8.0` and issue is still present. Thanks!

**Comment by alexeybusygin** [comment]
Unfortunately, I still have no luck trying to reproduce this problem. Will need some assistance from you if possible.
1. Do you get this error on both dev and production requests to FedEx?
2. Could you try downgrade ShippingRates to some previous versions (especially 1.0.5 and 1.0.0) and check if the error is still here?
