### ISSUE TITLE
Add optional USPS special services

### ISSUE THREAD

**Issue by justin-laird** [alexeybusygin/ShippingRates#20]
I'm not seeing a way to include USPS special services. More specifically I need to add Registered Mail Restricted Delivery. Any plans to make this available?

https://www.usps.com/business/web-tools-apis/rate-calculator-api.pdf - page 8

Special Service Name  |  ServiceID
Insurance  |  100
Insurance –Priority Mail Express  |  101
Return Receipt  |  102
Collect on Delivery  |  103
Certificate of Mailing (Form 3665)  |  104
Certified Mail  |  105
USPS Tracking  |  106
Signature Confirmation  |  108
Registered Mail  |  109
Return Receipt Electronic  |  110
Registered mail COD collection Charge  |  112
Return Receipt –Priority Mail Express  |  118
Adult Signature Required  |  119
Adult Signature Restricted Delivery  |  120
Insurance –Priority Mail  |  125
USPS Tracking Electronic  |  155
Signature Confirmation Electronic  |  156
Certificate of Mailing (Form 3817)  |  160
Certified Mail Restricted Delivery  |  170
Certified Mail Adult Signature Required  |  171
Certified Mail Adult Signature Restricted Delivery  |  172
Signature Confirm. Restrict. Delivery  |  173
Signature Confirmation Electronic Restricted Delivery  |  174
Collect on Delivery Restricted Delivery  |  175
Registered Mail Restricted Delivery  |  176
Insurance Restricted Delivery  |  177
Insurance Restrict.  Delivery –Priority Mail  |  179
Insurance Restrict. Delivery –Priority Mail Express  |  178
Insurance Restrict. Delivery (Bulk Only)  |  180
Scan Retention  |  181
Scan + Signature Retention  |  182
Special Handling -Fragile  |  190

**Comment by alexeybusygin** [comment]
USPS Special Services are available now since version 1.1.4. Here are the docs: https://github.com/alexeybusygin/ShippingRates/wiki/USPS-Special-Services
