### ISSUE TITLE
Calling GetRates(origin, destination, packages) from within a Blazor Component

### ISSUE THREAD

**Issue by fordbe** [alexeybusygin/ShippingRates#3]
Using a .net Core 3.1 app, I can successfully run the sample code and get rates back (testing with FedEx) when calling into my service that in turn calls GetRates(). If I move that call from the razor page into a server side blazor component, GetRates() stops responding (no exceptions to catch).

**Comment by alexeybusygin** [comment]
Does it return anything in the Errors or InternalErrors properties? I've added the Error Handling section to the Readme. Could you please also update to version 1.0.1, there was a possible bug with FedEx.

**Comment by fordbe** [comment]
Thanks. I will try the updated version and post the results along with any error handling info if needed.

**Comment by alexeybusygin** [comment]
Fixed in version 1.0.2.
