### ISSUE TITLE
No saturday delivery option

### ISSUE THREAD

**Issue by carloshgamboa** [alexeybusygin/ShippingRates#4]
Hi! I am trying to find a way to specify the option Saturday delivery. Any sugestions?
I will extend the package class to allow the boolean and add the code to GetRates.
Thanks a lot for maintaining this package!

**Comment by alexeybusygin** [comment]
Hi! Take a look at the saturday-delivery branch: https://github.com/alexeybusygin/ShippingRates/compare/saturday-delivery
It's just a draft yet, no tests, and FedEx only, but it works so far. There is a ShipmentOptions parameter for GetRates function and RateOption property for rate results. A call like this

```
var shipment = rateManager.GetRates(origin, destination, packages, new ShipmentOptions() {
    SaturdayDelivery = true,
    ShippingDate = new DateTime(2020, 7, 10)
});
```

will return something like this:

```
FedEx
        FIRST_OVERNIGHT
        FedEx First Overnight
        135.495
        7/11/2020 9:30:00 AM
        Saturday Delivery
FedEx
        PRIORITY_OVERNIGHT
        FedEx Priority Overnight
        107.55
        7/11/2020 12:00:00 PM
        Saturday Delivery
FedEx
        FIRST_OVERNIGHT
        FedEx First Overnight
        120.591
        7/13/2020 8:00:00 AM
        ...
```

Will it work for you?

**Comment by carloshgamboa** [comment]
Thank you Alexey, that would work for me, I appreciate your help :)

**Comment by alexeybusygin** [comment]
You are welcome, Carlos! I will include these changes in the next release of the ShippingRates.

**Comment by alexeybusygin** [comment]
The new NuGet package version 1.0.3 has been released with Saturday Delivery for FedEx, UPS and USPS.
