### ISSUE TITLE
Negotiated Rates

### ISSUE THREAD

**Issue by carloshgamboa** [alexeybusygin/ShippingRates#5]
Hello, I am having a hard time finding how to retrieve negotiated rates using ShippingRates.
Could you provide some info on how to retrieve it?

Thank you in advance! :)

**Comment by alexeybusygin** [comment]
Hello!

Could you please tell me if you use UPS or FedEx?

**Comment by carloshgamboa** [comment]
Actually both, but if you want to put an example with FedEx, I should be able to extrapolate the solution for UPS as well.

Thank you!

**Comment by alexeybusygin** [comment]
We already have negotiated rates implementation for UPS, you can enable it with UseNegotiatedRates property: https://github.com/alexeybusygin/ShippingRates/blob/2a29f709070a847ed23c8f230f34133fcf49584b/ShippingRates/ShippingProviders/UPSProvider.cs#L88
Could you please check if it works for you? I don't have a UPS account with negotiated rates enabled, so can't check it by myself.

**Comment by carloshgamboa** [comment]
I will test it soon, and I will let you know how it goes.
Do you have any plans for implementing negotiated rates for USPS and FedEx?

**Comment by alexeybusygin** [comment]
Yes, I will add the support for USPS and FedEx after DHL implementation will be completed.

**Comment by evik89** [comment]
Hello, Do you know when the FedEx negotiated rates will be available?

**Comment by alexeybusygin** [comment]
Hello,
Sorry for the delay. I expect FedEx negotiated rates to be completed in April.

**Comment by joekrauss** [comment]
Hello - Can you include FedEx One Rate services and pricing? The information is provided directly from FedEx web service online documentation. Thanks!

How to Specify One Rate Pricing
To specify FedEx One Rate Pricing Option in the Web Service Transaction, do the following:
1.     Specify FEDEX_ONE_RATE Shipment Special Service.
2.     Specify one of the following Packaging Types:

Packaging Type | Max Weight (lbs) | Max Weight (kg)
FEDEX_SMALL_BOX | 50 | 22.68
FEDEX_MEDIUM_BOX | 50 | 22.68
FEDEX_LARGE_BOX | 50 | 22.68
FEDEX_EXTRA_LARGE_BOX | 50 | 22.68
FEDEX_PAK | 50 | 22.68
FEDEX_TUBE | 50 | 22.68
FEDEX_ENVELOPE | 10 | 4.5

**Comment by DavidShochet** [comment]
Здравствуйте, Алексей!

I am trying to use your solution for getting negotiated rates:

            rateManager.AddProvider(new UPSProvider(upsLicenseNumber, upsUsername, upsPassword) { UseNegotiatedRates = true, UseProduction = false });

But the rate I get back is the same, whether UseNegotiatedRates is true of false. I guess, ShipperNumber should be required, but if so, where can I provide it? Or anything else I may be missing?

Also, I see your package deals with UPS packages, but how about freight?

Thank you very much!

**Comment by alexeybusygin** [comment]
Negotiated Rates support added for FedEx, and discounted rates support added for USPS: https://github.com/alexeybusygin/ShippingRates/wiki/Negotiated-Rates
