### ISSUE TITLE
DotNetShipping: The request was aborted: Could not create SSL/TLS secure channel. Canada orders yield errors

### ISSUE THREAD

**Issue by federico-aguilar** [alexeybusygin/ShippingRates#51]
Hi community,
I've been trying to resolve this issue by reading the UPS docs and looking over the code in this repository but to no avail. Has anyone else had issues getting back rates for Canadian orders? This issue is an extremely interesting one because US orders work just fine but as soon as I put in a Canadian address, BAM. Errors. Please refer to my stackoverflow post: https://stackoverflow.com/questions/75584440/dotnetshipping-the-request-was-aborted-could-not-create-ssl-tls-secure-channel

**Comment by alexeybusygin** [comment]
Hi, is it possible for you to upgrade to ShippingRates and check the request here? We are keeping compatibility with .NET Framework 4.6.1 and higher.
