### ISSUE TITLE
UPS deprecating  xml API on June 5,2024

### ISSUE THREAD

**Issue by bgiromini** [alexeybusygin/ShippingRates#52]
Got this email from UPS today:

> Upgrades to the UPS API Security Model
>  
> Thank you for being a UPS API user! At UPS, we continue to improve our technology offerings and work to provide better security for our valued customers. 
> 
> UPS has implemented an OAuth 2.0 security model for all APIs to enhance the overall security for our customers to reduce fraud and provide enhanced API capabilities. This change impacts your current API integration and requires you to make updates to your existing application interface. 
> 
> How will this impact my API integration?  
> 
> • Beginning June 5, 2023, UPS will no longer issue API access keys
> 
> • On June 3, 2024, access keys will no longer be supported for authentication to UPS APIs
> 
> • You will need to obtain OAuth API credentials from the new UPS Developer Portal and update your security protocols to OAuth 2.0 prior to June 3, 2024 to continue transacting with UPS APIs
> 
> • Any legacy UPS API integrations using XML, SOAP, or legacy JSON payloads will also be required to convert to the RESTful APIs
> 
> We have created an API access key migration guide to assist with your migration from access keys to OAuth 2.0. If you obtained an access key to provide to a 3rd party please notify them of these changes immediately. 
> 

So this means this package will need to implement the Rest api or it will no longer work on June 5, 2023.

**Comment by peterped-dev** [comment]
Any plans to support the new UPS requirement for OAuth mentioned here?

**Comment by alexeybusygin** [comment]
The work is in progress here. We expect it to be done by the end of January.

**Comment by alexeybusygin** [comment]
Unfortunately, I am having issues obtaining OAuth API credentials as we no longer have a contract with UPS. That's actually blocking the development of this feature. If anyone can provide me with the UPS OAuth API credentials, it would help a lot. Please feel free to reach me via alexey@busygin.com

**Comment by alexeybusygin** [comment]
The beta version of the new UPS OAuth 2.0 Security Model is ready for review: https://www.nuget.org/packages/ShippingRates/2.0.215-beta

**Comment by bgiromini** [comment]
I will have my team test these changes this week and let you know if we have any issues.

**Comment by owi2000** [comment]
Switched over to the beta build and have been trying to test.  Got Id and Secret values from UPS and changed the authentication as directed, however I'm not able to get rates.  Not getting errors either, it's just hanging for me when I call the rateManager.GetRates().

**Comment by alexeybusygin** [comment]
> Switched over to the beta build and have been trying to test. Got Id and Secret values from UPS and changed the authentication as directed, however I'm not able to get rates. Not getting errors either, it's just hanging for me when I call the rateManager.GetRates().

Could you please try the latest beta: https://www.nuget.org/packages/ShippingRates/2.0.217-beta
And check shipment.InternalErrors if the issues are still there.

**Comment by bgiromini** [comment]
My team did a test and was able to successfully connect and get back rates.
HOWEVER, even though we indicated we wanted negotiated rates, the rates
barely changed. I will have to ask my co-worker but I am fairly certain he
did a fiddler and verified the indicator was being passed correctly. ALSO,
the URL is hard-coded to connect to the CIE environment, so we could not
move forward to use it in production. I verified via direct use that the
negotiated rates were in effect drastically different from what the
GetRates() method was returning.

**Comment by owi2000** [comment]
Regarding the negotiated rates, I contacted UPS about that and it's something wrong on their end they need to address.  I found this when I was able to get rates in Postman.  However I'm still unable to get any sort of result using this package.  I'm thinking the issue is probably that our website is quite dated, and some of the packages required for this probably aren't compatible even though we're on .net4.6.1.

**Comment by alexeybusygin** [comment]
> ALSO, the URL is hard-coded to connect to the CIE environment, so we could not move forward to use it in production. 

That's fixed in version [2.0.218-beta](https://www.nuget.org/packages/ShippingRates/2.0.218-beta). Now, there is a UseProduction parameter in the UPSProviderConfiguration.

**Comment by alexeybusygin** [comment]
Released in version [2.1.0](https://www.nuget.org/packages/ShippingRates/2.1.0).
