### ISSUE TITLE
UPS ServiceDescription Bug

### ISSUE THREAD

**Issue by owi2000** [alexeybusygin/ShippingRates#60]
There appears to be a bug in the way the ServiceDescription is used in the UPSProvider class.  Service description is used to determine the value of the RequestOption in the following code:
`writer.WriteElementString("RequestOption", string.IsNullOrWhiteSpace(_serviceDescription) ? "Shop" : _serviceDescription);`
The values for this field should either be "Shop" or "Rate" as far as I know.  

However, the ServiceDescription is also used to determine the ServiceCode if you're specifying a shipping method:
`writer.WriteElementString("Code", _serviceDescription.ToUpsShipCode());`

"Rate" is not a valid entry for the ToUpsShipCode() function, and any ship method (i.e. "UPS Sure Post") is not a valid entry for RequestOption.  This needs to be fixed.

**Comment by alexeybusygin** [comment]
ServiceDescription is expected to have a UPS shipping method code or name as a parameter, one of these values:
https://github.com/alexeybusygin/ShippingRates/blob/e956efe0600a35c8bb4dc8710e8b27b9eb9576c0/ShippingRates/ShippingProviders/UPSProvider.cs#L19-L37

**Comment by alexeybusygin** [comment]
That's finally fixed in the version [2.1.0](https://www.nuget.org/packages/ShippingRates/2.1.0)
