### ISSUE TITLE
Example Getting Started does not work for UPS-Rates

### ISSUE THREAD

**Issue by ebaj-tech** [alexeybusygin/ShippingRates#66]
Hello everyone,

I'm having trouble getting the 'Getting Started' example for UPS shipping to work. I keep receiving the following error message: 

- Error Code: 250002 
- Error Description: Invalid Authentication Information 

Is this example supposed to work with OAuth2.0?

**Comment by alexeybusygin** [comment]
Yes, since version 2.1.0, only OAuth 2.0 has been supported for UPS. Error 250002 is quite generic and can have at least two reasons:
* Credentials are incorrect.
* Rating API permissions were not added to the app.

**Comment by ebaj-tech** [comment]
I found the reason for the error message. On the UPS website, the required API also needs to be selected, in this case, Rating.

![image](https://github.com/user-attachments/assets/bf913685-a2df-4fba-b4aa-80a5fbd7a1d9)
