### ISSUE TITLE
UPS CustomerClassification is ignored

### ISSUE THREAD

**Issue by ebaj-tech** [alexeybusygin/ShippingRates#81]
Any setting of the property UPSProviderConfiguration.CustomerClassification is ignored if shipment.OriginAddress.CountryCode is not "US". Could you please check the method Build() in the class UpsRatingRequestBuilder? The following lines of code are only executed if shipFromUS is true:
```
var code = ((int)customerClassification).ToString("D2");
request.RateRequest.CustomerClassification = new CustomerClassification() { Code = code };
```
In my opinion, there should always be a new object of CustomerClassification() { Code = code }. If I ignore the value of shipFromUS, then the response is correct.

**Comment by alexeybusygin** [comment]
That's what UPS has in the documentation:
![image](https://github.com/user-attachments/assets/2dd6abb6-d5e7-4f10-9b12-82e9b161e920)

Do I understand you correctly that API processes CustomerClassification even if the sender's country is not the US?

**Comment by ebaj-tech** [comment]
Yes, that's correct. And I can see now that it's described differently in the documentation. But in the old API interface I always had to set the value for CustomerClassification to "53". This gave us the standard list prices. Without this value "53" the prices are too low. This seems to be the same for the ShippingRates Nuget package. For example, if the origin address and the delivery address are in Germany, then it makes a big price difference whether I set CustomerClassification to "53" or not.

**Comment by ebaj-tech** [comment]
If the UPS documentation was correct, it would mean that there would only be standard rates for the US. That doesn't seem to be correctly described to me.

**Comment by ebaj-tech** [comment]
Here's something else interesting. The API also gives me the correct standard list price in the following configuration:
UseNegotiatedRates = false, CustomerClassification = "00"
But currently the value for CustomerClassification can only be set within US shipping if(shipFromUS == true).
I hope that helps you.

**Comment by alexeybusygin** [comment]
Could you please check the latest version 2.2.3? It should now pass CustomerClassification for all shipments.

**Comment by ebaj-tech** [comment]
It works just fine! Thank you for implementing this feature!
